server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-message: always
    include-binding-errors: always
    #include-stacktrace: on_trace_param
    include-exception: false

spring:
  application:
    name: idea-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/idea_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bies-realm

kafka:
  topic-name: notification_topic
  producer:
    bootstrap-servers: localhost:9092