databaseChangeLog:
  - changeSet:
      id: set-compose-pk-votes-table
      author: admin
      changes:
        - addPrimaryKey:
            columnNames: "idea_id, user_id"
            constraintName: "PK"
            tableName: votes